import React from "react";
// TODO: Replace these placeholders with actual, high-quality SVG icons or icon components.
const PlaceholderIcon1 = () => (
  <svg
    className="w-10 h-10"
    /* Add SVG content */ viewBox="0 0 24 24"
    strokeWidth="1.5"
    stroke="currentColor"
    fill="none"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
    <path d="M4 8v-2a2 2 0 0 1 2 -2h2" />
    <path d="M4 16v2a2 2 0 0 0 2 2h2" />
    <path d="M16 4h2a2 2 0 0 1 2 2v2" />
    <path d="M16 20h2a2 2 0 0 0 2 -2v-2" />
    <path d="M12 12v.01" />
    <path d="M12 18v.01" />
    <path d="M12 6v.01" />
  </svg>
);
const PlaceholderIcon2 = () => (
  <svg
    className="w-10 h-10"
    /* Add SVG content */ viewBox="0 0 24 24"
    strokeWidth="1.5"
    stroke="currentColor"
    fill="none"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
    <path d="M16.71 13.71l-2.71 2.79l-2.71 -2.79a1 1 0 0 0 -1.41 -.11a1 1 0 0 0 -.11 1.41l4.11 4.11l4.11 -4.11a1 1 0 0 0 -.1 -1.41a1 1 0 0 0 -1.41 .1z" />
    <path d="M16.71 7.71l-2.71 2.79l-2.71 -2.79a1 1 0 0 0 -1.41 -.11a1 1 0 0 0 -.11 1.41l4.11 4.11l4.11 -4.11a1 1 0 0 0 -.1 -1.41a1 1 0 0 0 -1.41 .1z" />
  </svg>
);
const PlaceholderIcon3 = () => (
  <svg
    className="w-10 h-10"
    /* Add SVG content */ viewBox="0 0 24 24"
    strokeWidth="1.5"
    stroke="currentColor"
    fill="none"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
    <path d="M8 16v.01" />
    <path d="M8 12v.01" />
    <path d="M8 8v.01" />
    <path d="M12 16v.01" />
    <path d="M12 12v.01" />
    <path d="M12 8v.01" />
    <path d="M16 16v.01" />
    <path d="M16 12v.01" />
    <path d="M16 8v.01" />
  </svg>
);

// FeatureColumn: Reintroducing cards with top border accent
const FeatureColumn = ({ icon, title, description }) => (
  // Card container with white background, subtle shadow, more padding, and top border accent
  <div className="bg-yellow-400 rounded-xl shadow-sm p-6 md:p-8 text-center h-full flex flex-col items-center border border-t-4 border-t-black hover:shadow-md transition-shadow duration-300">
    {/* Icon Container: Keep refined style */}
    <div className="mb-6 inline-flex items-center justify-center w-20 h-20 rounded-full bg-gradient-to-br from-gray-50 to-gray-200 border border-gray-200 text-gray-600 shadow-sm">
      {icon || "?"}
    </div>

    {/* No divider needed if using card structure */}
    {/* <hr className="w-16 mx-auto my-5 border-gray-300" /> */}

    {/* Title */}
    <h3 className="text-xl font-semibold text-gray-800 mb-3">{title}</h3>

    {/* Description */}
    <p className="text-gray-600 text-base leading-relaxed flex-grow">
      {description}
    </p>
  </div>
);

const HowItWorks = ({
  heading = "How It Works",
  // Expects array: [{ icon: <JSX>, title: string, description: string }, ...]
  features = [],
}) => {
  // Example data structure
  const exampleFeatures = [
    {
      icon: <PlaceholderIcon1 />,
      title: "Radar Sensor",
      description:
        "Detects termite movement through walls, floors, and ceilings without penetration using microwave signals.",
    },
    {
      icon: <PlaceholderIcon2 />,
      title: "Moisture & Temp",
      description:
        "Pinpoints moisture and temperature differentials often associated with termite infestations.",
    },
    {
      icon: <PlaceholderIcon3 />,
      title: "Thermal Sensor",
      description:
        "Identifies heat signatures generated by termite colonies, revealing hidden activity.",
    },
  ];

  const featuresToDisplay = features.length > 0 ? features : exampleFeatures;

  return (
    // Section with light gray background
    <section className="py-16 lg:py-24 bg-gray-100">
      {" "}
      {/* Keep light gray bg */}
      <div className="container mx-auto px-6">
        <h2 className="text-3xl md:text-4xl font-bold text-center text-gray-800 mb-16 lg:mb-20">
          {heading}
        </h2>
        {/* Grid with increased gap */}
        <div
          className={`grid grid-cols-1 ${
            featuresToDisplay.length >= 2 ? "md:grid-cols-2" : ""
          } ${
            featuresToDisplay.length >= 3 ? "lg:grid-cols-3" : ""
          } gap-8 md:gap-10 items-stretch`}
        >
          {" "}
          {/* Increased gap slightly */}
          {featuresToDisplay.map((feature, index) => (
            <FeatureColumn
              key={index}
              icon={feature.icon}
              title={feature.title}
              description={feature.description}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default HowItWorks;
